FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy

# set version label
ARG BUILD_DATE
ARG VERSION
ARG CODE_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="aptalca"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config"

USER root

RUN \
  echo "**** install runtime dependencies ****" && \
  apt-get update && \
  apt-get install -y \
    git \
    jq \
    libatomic1 \
    nano \
    net-tools \
    netcat \
    python3 \ 
    python3-dev \ 
    python3-pip \
    zip \
    unzip \
    curl \
    wget \
    sudo && apt-get clean \
    echo "**** install code-server ****" && \
    mkdir -p /app/code-server


RUN mkdir -p /opt/miniconda3
ENV PATH=/opt/miniconda3/bin:${PATH}
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /opt/miniconda/miniconda.sh
RUN bash /opt/miniconda3/miniconda.sh -b -u -p /opt/miniconda3
RUN rm -rf /opt/miniconda3/miniconda.sh

#RUN cp /usr/local/bin/gunicorn /opt/miniconda/bin/



#RUN /opt/miniconda/bin/conda init bash
# 创建base环境
#RUN conda create --name base python=3.11 
# 激活slab环境
#RUN conda activate base
# 安装python库
RUN pip install python-dotenv requests pandas


# 安装Code-Server
RUN curl -o /tmp/code-server.tar.gz -L "https://github.com/coder/code-server/releases/download/v4.90.3/code-server-4.90.3-linux-arm64.tar.gz"
RUN tar xf /tmp/code-server.tar.gz -C /app/code-server --strip-components=1

RUN rm -rf /config/* /tmp/* /var/lib/apt/lists/* /var/tmp/*

ENV PATH=/app/code-server/bin:$PATH
  
# add local files
COPY /root /

# ports and volumes
EXPOSE 8443
